/**
 * Tag Taxonomy
 *
 * Defines a 2-level parent > child hierarchy for tags.
 */

/** Convert kebab-case tag to plain language */
export function tagToLabel(tag: string): string {
  return tag
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

/** Tag category definition */
export interface TagCategory {
  id: string
  label: string
  children: string[]
}

/**
 * Tag Taxonomy - categories and their child tags
 */
export const TAG_TAXONOMY: TagCategory[] = [
  {
    id: 'type',
    label: 'Type',
    children: [
      'character',
      'location',
      'person',
      'item',
      'organization',
      'book',
      'movie',
      'vehicle',
      'franchise',
      'company',
      'artifact',
    ],
  },
  {
    id: 'genre',
    label: 'Genre',
    children: [
      'action',
      'adventure',
      'comedy',
      'crime',
      'drama',
      'fantasy',
      'horror',
      'mystery',
      'romance',
      'sci-fi',
      'science-fiction',
      'thriller',
      'western',
      'noir',
      'espionage',
      'spy-fiction',
      'cyberpunk',
      'heist',
      'satire',
      'musical',
      'animation',
      'documentary',
      'war',
      'biographical',
    ],
  },
  {
    id: 'era',
    label: 'Era',
    children: [
      'ancient',
      'medieval',
      'renaissance',
      'victorian',
      'edwardian',
      '1920s',
      '1930s',
      '1940s',
      '1950s',
      '1960s',
      '1970s',
      '1980s',
      '1990s',
      '2000s',
      '2010s',
      '2020s',
      'cold-war',
      'post-war',
      'futuristic',
      'near-future',
      'far-future',
      'timeless',
    ],
  },
  {
    id: 'tone',
    label: 'Tone',
    children: [
      'dark',
      'light',
      'gritty',
      'whimsical',
      'cerebral',
      'atmospheric',
      'suspenseful',
      'tense',
      'dramatic',
      'comedic',
      'tragic',
      'epic',
      'intimate',
      'surreal',
      'dreamlike',
      'nostalgic',
      'melancholic',
      'hopeful',
      'bleak',
      'campy',
      'satirical',
      'heartfelt',
      'serious',
    ],
  },
  {
    id: 'theme',
    label: 'Theme',
    children: [
      'loyalty',
      'betrayal',
      'redemption',
      'revenge',
      'justice',
      'corruption',
      'power',
      'ambition',
      'family',
      'identity',
      'sacrifice',
      'survival',
      'freedom',
      'isolation',
      'obsession',
      'paranoia',
      'morality',
      'deception',
      'trust',
      'honor',
      'duty',
      'legacy',
      'fate',
      'destiny',
      'love',
      'loss',
      'grief',
      'hope',
      'fear',
      'greed',
      'transformation',
      'coming-of-age',
    ],
  },
  {
    id: 'franchise',
    label: 'Franchise',
    children: [
      'batman',
      'dc-universe',
      'dark-knight',
      'gotham',
      'james-bond',
      '007',
      'mi6',
      'back-to-the-future',
      'hill-valley',
      'the-godfather',
      'corleone',
      'middle-earth',
      'lord-of-the-rings',
      'the-hobbit',
      'foundation',
      'discworld',
      'sherlock-holmes',
      'neuromancer',
      'inception',
      'tenet',
      'interstellar',
      'the-prestige',
      'oppenheimer',
      'christopher-nolan',
    ],
  },
  {
    id: 'role',
    label: 'Role',
    children: [
      'actor',
      'actress',
      'director',
      'writer',
      'producer',
      'scientist',
      'spy',
      'detective',
      'mobster',
      'soldier',
      'agent',
      'assassin',
      'thief',
      'lawyer',
      'doctor',
      'politician',
      'journalist',
      'engineer',
      'pilot',
      'butler',
      'mentor',
      'villain',
      'hero',
      'antihero',
    ],
  },
  {
    id: 'trait',
    label: 'Trait',
    children: [
      'loyal',
      'brave',
      'cunning',
      'wise',
      'cruel',
      'ruthless',
      'ambitious',
      'charismatic',
      'intelligent',
      'resourceful',
      'determined',
      'manipulative',
      'mysterious',
      'enigmatic',
      'charming',
      'witty',
      'arrogant',
      'stoic',
      'eccentric',
      'calculating',
      'patient',
      'fierce',
      'cold',
      'clever',
      'cynical',
      'idealistic',
      'pragmatic',
      'honorable',
      'fearless',
      'compassionate',
      'vengeful',
    ],
  },
]

/** Get category by ID */
export function getCategory(id: string): TagCategory | undefined {
  return TAG_TAXONOMY.find(c => c.id === id)
}

/** Get all category IDs */
export function getCategoryIds(): string[] {
  return TAG_TAXONOMY.map(c => c.id)
}
